### ISSUE TITLE
Assertion for `X-Frame-Options` is too rigid

### ISSUE THREAD

**Issue by CalgaryMichael** [oshp/oshp-validator#1]
When using this tool against my company's website, I noticed that `X-Frame-Options` fails unless the header explicitly matches the literal value `deny`. I think this should be relaxed a bit to also succeed on `DENY`, as this is a valid option and matches more directly the variable outlined in the original [RFC].

Changing this assertion to a `ShouldBeIn` to succeed on both values would be the best option in my mind. I will go ahead and open a PR to change this assertion

[RFC]: https://www.rfc-editor.org/rfc/rfc7034#section-2

**Comment by righettod** [comment]
Hi @CalgaryMichael ,

You have 100% right, thank a lot for the issue and your PR 👍

**Comment by righettod** [comment]
PR merged, thank again for it 😃
