### ISSUE TITLE
[BUG] Fix quoting of variables in test suite

### ISSUE THREAD

**Issue by JensSkipr** [oshp/oshp-validator#3]
**Describe the bug**

Currently the test suite is not a valid YAML file, due to missing quoting of variables.

**To Reproduce**
1. Go to e.g. https://www.yamllint.com/
2. Paste `test_suite.yml`
3. Click `Go` button

**Expected behavior**

In case the file is valid YAML, we can script updates on it to adapt to specific needs while still receiving upstream updates. Also, formatting in IDE seems not to work on an invalid file.

**Screenshots**
![image](https://user-images.githubusercontent.com/62247524/233623399-a5d64e4f-5577-4978-bf8e-3e0621a9509f.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by righettod** [comment]
Hi,

Thank you very much for the PR and the fix 😃 

I merged the PR.

**Comment by righettod** [comment]
@JensSkipr 
Based on your feedback, I added the linter check in the CI pipeline with [yamllint](https://yamllint.readthedocs.io) .
Thank again your precious feedback and PR 💯
