### ISSUE TITLE
[BUG] space character in Strict-Transport-Security

### ISSUE THREAD

**Issue by christophvw** [oshp/oshp-validator#5]
ShouldEqual "max-age=31536000 ; includeSubDomains"

should be changed to 

ShouldEqual "max-age=31536000; includeSubDomains"

without the space.

IIS sends it without space, Mozilla documentation describes the syntax without space characeter as well:
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security

**Comment by righettod** [comment]
Hi,
Thanks for reporting 👍

**Comment by righettod** [comment]
PR opened in main repo: https://github.com/OWASP/www-project-secure-headers/pull/162

**Comment by righettod** [comment]
Fix added into this repo for the validation via the commit https://github.com/oshp/oshp-validator/commit/c3befa0633839ff7fe3b83ca6566abe77595b8dd

**Comment by righettod** [comment]
✅ Fixed
