### ISSUE TITLE
[BUG] FAIL on lower case headers

### ISSUE THREAD

**Issue by HugoVG** [oshp/oshp-validator#8]
**Describe the bug**
Test suite returns false negatives when lowercase headers are used
https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2
> Just as in HTTP/1.x, header field names are strings of ASCII
   characters that are compared in a **case-insensitive** fashion.  However,
   header field names MUST be converted to lowercase prior to their
   encoding in HTTP/2.  A request or response containing uppercase
   header field names MUST be treated as malformed.

When running oshp yml with venom

Headers:

strict-transport-security | max-age=63072000; includeSubDomains; preload
x-frame-options | DEN

Actual:

```sh
• Strict-Transport-Security FAIL
Testcase "Strict-Transport-Security", step #0-0: Assertion "result.headers.Strict-Transport-Security ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:16)
Testcase "Strict-Transport-Security", step #0-0: Assertion "result.headers.Strict-Transport-Security ShouldEqual \"max-age=31536000; includeSubDomains\"" failed. expected: max-age=31536000; includeSubDomains  got: <nil> (owasp.securityheader.yml:17)
        
• X-Frame-Options FAIL
Testcase "X-Frame-Options", step #0-0: Assertion "result.headers.X-Frame-Options ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:27)
Testcase "X-Frame-Options", step #0-0: Assertion "result.headers.X-Frame-Options ShouldBeIn \"deny\" \"DENY\"" failed. expected '<nil>' in [deny DENY] but it wasnt (owasp.securityheader.yml:28)
```

Also I think I found a typo
`` failed. expected: Not Nil but is was ``
is supposed to be 
`` failed. expected: Not Nil but **it** was``

**To Reproduce**
1. Download venom (in my case linux-x64)
2. Grab the test_suit.yml from this github
3. ``venom run --var="target_site=https://owasp.org" owasp.securityheader.yml`` (I renamed my file)
4. get a bunch of fails due to case insensitivity

**Expected behavior**
To not not throw false positives when working with headers.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows WSL2-Ubuntu
 - Browser: CLI
 - Version: tests_suite.yml of Oct 19

**Comment by righettod** [comment]
Hello,

Thanks a lot for the bug report, I will work on it and keep you informed.

**Comment by righettod** [comment]
Just a tiny question: Which version of **venom** have you used?

**Comment by righettod** [comment]
I have tested using the latest version of venom on Windows 10 Pro using test suites from the GitHub repository and I did not face the problem mentioned:

![image](https://github.com/user-attachments/assets/ab9aa309-a30f-4f8d-8ec9-66a3cecf7635)

Same result on a Linux machine:

![image](https://github.com/user-attachments/assets/63bb7322-eb9a-4269-b4e8-a67756eb6e75)

🤔Do you used [the latest version](https://github.com/ovh/venom/releases) of venom ?

**Comment by HugoVG** [comment]
Yes I first heard about venom about yesterday and wanted to try it, I was using the latest version
It's kinda odd, can you try testing it against the owasp.org homepage or google.com? I want to make sure it is not an issue on my end 😅

**Comment by righettod** [comment]
No problem, I will perform more tests and keep you updated. Thanks for your feedback.

**Comment by righettod** [comment]
📖Test on https://owasp.org returning the following headers:

![image](https://github.com/user-attachments/assets/50a2aabe-fb8b-4789-87ad-802d0525bac7)

💻Venom run:

![image](https://github.com/user-attachments/assets/6ed56ed3-188c-410d-b2dc-677fe77044af)

📖Test on https://www.google.com/ returning the following headers:

![image](https://github.com/user-attachments/assets/1f106433-05dc-4414-9484-768acad6ff1d)

💻Venom run:

![image](https://github.com/user-attachments/assets/63c11072-52d2-4b6b-afb6-b8f6c68b4527)

🤔For me, venom and the test suites behaves as expected: Did I miss something?

**Comment by HugoVG** [comment]
That's weird let me write my logs
```sh
venom version
Version venom: v1.1.0
```

<details>
<summary>test_suite.yml</summary>
name: HTTP security response headers test suites
vars:
  target_site: ''
  logout_url: ''
  request_timeout_in_seconds: 20
testcases:
  - name: Strict-Transport-Security
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}'
        skip_body: true
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.Strict-Transport-Security ShouldNotBeNil
          - result.headers.Strict-Transport-Security ShouldEqual "max-age=31536000; includeSubDomains"
  - name: X-Frame-Options
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}'
        skip_body: true
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.X-Frame-Options ShouldNotBeNil
          - result.headers.X-Frame-Options ShouldBeIn "deny" "DENY"
  - name: X-Content-Type-Options
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}'
        skip_body: true
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.X-Content-Type-Options ShouldNotBeNil
          - result.headers.X-Content-Type-Options ShouldEqual "nosniff"
  - name: Content-Security-Policy
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}'
        skip_body: true
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.Content-Security-Policy ShouldNotBeNil
          - result.headers.Content-Security-Policy ShouldNotContainSubstring "unsafe"
  - name: X-Permitted-Cross-Domain-Policies
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}'
        skip_body: true
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.X-Permitted-Cross-Domain-Policies ShouldNotBeNil
          - result.headers.X-Permitted-Cross-Domain-Policies ShouldEqual "none"
  - name: Referrer-Policy
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}'
        skip_body: true
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.Referrer-Policy ShouldNotBeNil
          - result.headers.Referrer-Policy ShouldEqual "no-referrer"
  - name: Clear-Site-Data
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}/{{.logout_url}}'
        skip_body: true
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.Clear-Site-Data ShouldNotBeNil
          - result.headers.Clear-Site-Data ShouldEqual '"cache","cookies","storage"'
  - name: Cross-Origin-Embedder-Policy
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}'
        skip_body: true
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.Cross-Origin-Embedder-Policy ShouldNotBeNil
          - result.headers.Cross-Origin-Embedder-Policy ShouldEqual "require-corp"
  - name: Cross-Origin-Opener-Policy
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}'
        skip_body: true
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.Cross-Origin-Opener-Policy ShouldNotBeNil
          - result.headers.Cross-Origin-Opener-Policy ShouldEqual "same-origin"
  - name: Cross-Origin-Resource-Policy
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}'
        skip_body: true
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.Cross-Origin-Resource-Policy ShouldNotBeNil
          - result.headers.Cross-Origin-Resource-Policy ShouldEqual "same-origin"
  - name: Permissions-Policy
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}'
        skip_body: true
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.Permissions-Policy ShouldNotBeNil
          - result.headers.Permissions-Policy ShouldEqual "accelerometer=(), autoplay=(), camera=(), cross-origin-isolated=(), display-capture=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(self), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(), clipboard-write=(), gamepad=(), hid=(), idle-detection=(), interest-cohort=(), serial=(), unload=()"
  - name: Cache-Control
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}'
        skip_body: true
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.Cache-Control ShouldNotBeNil
          - 'result.headers.Cache-Control ShouldEqual "no-store, max-age=0"'
  - name: Feature-Policy
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}'
        skip_body: true
        info: >-
          This header has now been renamed to Permissions-Policy in the
          specification.
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.Feature-Policy ShouldBeNil
  - name: Public-Key-Pins
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}'
        skip_body: true
        info: >-
          This header has been deprecated by all major browsers and is no longer
          recommended. Avoid using it, and update existing code if possible!
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.Public-Key-Pins ShouldBeNil
  - name: Expect-CT
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}'
        skip_body: true
        info: >-
          This header will likely become obsolete in June 2021. Since May 2018
          new certificates are expected to support SCTs by default. Certificates
          before March 2018 were allowed to have a lifetime of 39 months, those
          will all be expired in June 2021.
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.Expect-CT ShouldBeNil
  - name: X-XSS-Protection
    steps:
      - type: http
        method: GET
        url: '{{.target_site}}'
        skip_body: true
        info: >-
          The X-XSS-Protection header has been deprecated by modern browsers and
          its use can introduce additional security issues on the client side.
        timeout: '{{.request_timeout_in_seconds}}'
        assertions:
          - result.statuscode ShouldEqual 200
          - result.headers.X-XSS-Protection ShouldBeNil

</details>

<details>
<summary>Venom run google.com</summary>
venom run --var="target_site=https://google.com" owasp.securityheader.yml


          [trac] writing venom.11.log
 • HTTP security response headers test suites (owasp.securityheader.yml)
        • Strict-Transport-Security FAIL
Testcase "Strict-Transport-Security", step #0-0: Assertion "result.headers.Strict-Transport-Security ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:16)
Testcase "Strict-Transport-Security", step #0-0: Assertion "result.headers.Strict-Transport-Security ShouldEqual \"max-age=31536000; includeSubDomains\"" failed. expected: max-age=31536000; includeSubDomains  got: <nil> (owasp.securityheader.yml:17)
        • X-Frame-Options FAIL
Testcase "X-Frame-Options", step #0-0: Assertion "result.headers.X-Frame-Options ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:27)
Testcase "X-Frame-Options", step #0-0: Assertion "result.headers.X-Frame-Options ShouldBeIn \"deny\" \"DENY\"" failed. expected '<nil>' in [deny DENY] but it wasnt (owasp.securityheader.yml:28)
        • X-Content-Type-Options FAIL
Testcase "X-Content-Type-Options", step #0-0: Assertion "result.headers.X-Content-Type-Options ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:38)
Testcase "X-Content-Type-Options", step #0-0: Assertion "result.headers.X-Content-Type-Options ShouldEqual \"nosniff\"" failed. expected: nosniff  got: <nil> (owasp.securityheader.yml:39)
        • Content-Security-Policy FAIL
Testcase "Content-Security-Policy", step #0-0: Assertion "result.headers.Content-Security-Policy ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:49)
        • X-Permitted-Cross-Domain-Policies FAIL
Testcase "X-Permitted-Cross-Domain-Policies", step #0-0: Assertion "result.headers.X-Permitted-Cross-Domain-Policies ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:60)
Testcase "X-Permitted-Cross-Domain-Policies", step #0-0: Assertion "result.headers.X-Permitted-Cross-Domain-Policies ShouldEqual \"none\"" failed. expected: none  got: <nil> (owasp.securityheader.yml:61)
        • Referrer-Policy FAIL
Testcase "Referrer-Policy", step #0-0: Assertion "result.headers.Referrer-Policy ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:71)
Testcase "Referrer-Policy", step #0-0: Assertion "result.headers.Referrer-Policy ShouldEqual \"no-referrer\"" failed. expected: no-referrer  got: <nil> (owasp.securityheader.yml:72)
        • Clear-Site-Data FAIL
Testcase "Clear-Site-Data", step #0-0: Assertion "result.headers.Clear-Site-Data ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:82)
Testcase "Clear-Site-Data", step #0-0: Assertion "result.headers.Clear-Site-Data ShouldEqual '\"cache\",\"cookies\",\"storage\"'" failed. expected: "cache","cookies","storage"  got: <nil> (owasp.securityheader.yml:83)
        • Cross-Origin-Embedder-Policy FAIL
Testcase "Cross-Origin-Embedder-Policy", step #0-0: Assertion "result.headers.Cross-Origin-Embedder-Policy ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:93)
Testcase "Cross-Origin-Embedder-Policy", step #0-0: Assertion "result.headers.Cross-Origin-Embedder-Policy ShouldEqual \"require-corp\"" failed. expected: require-corp  got: <nil> (owasp.securityheader.yml:94)
        • Cross-Origin-Opener-Policy FAIL
Testcase "Cross-Origin-Opener-Policy", step #0-0: Assertion "result.headers.Cross-Origin-Opener-Policy ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:104)
Testcase "Cross-Origin-Opener-Policy", step #0-0: Assertion "result.headers.Cross-Origin-Opener-Policy ShouldEqual \"same-origin\"" failed. expected: same-origin  got: <nil> (owasp.securityheader.yml:105)
        • Cross-Origin-Resource-Policy FAIL
Testcase "Cross-Origin-Resource-Policy", step #0-0: Assertion "result.headers.Cross-Origin-Resource-Policy ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:115)
Testcase "Cross-Origin-Resource-Policy", step #0-0: Assertion "result.headers.Cross-Origin-Resource-Policy ShouldEqual \"same-origin\"" failed. expected: same-origin  got: <nil> (owasp.securityheader.yml:116)
        • Permissions-Policy FAIL
Testcase "Permissions-Policy", step #0-0: Assertion "result.headers.Permissions-Policy ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:126)
Testcase "Permissions-Policy", step #0-0: Assertion "result.headers.Permissions-Policy ShouldEqual \"accelerometer=(), autoplay=(), camera=(), cross-origin-isolated=(), display-capture=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(self), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(), clipboard-write=(), gamepad=(), hid=(), idle-detection=(), interest-cohort=(), serial=(), unload=()\"" failed. expected: accelerometer=(), autoplay=(), camera=(), cross-origin-isolated=(), display-capture=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(self), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(), clipboard-write=(), gamepad=(), hid=(), idle-detection=(), interest-cohort=(), serial=(), unload=()  got: <nil> (owasp.securityheader.yml:127)
        • Cache-Control FAIL
Testcase "Cache-Control", step #0-0: Assertion "result.headers.Cache-Control ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:137)
Testcase "Cache-Control", step #0-0: Assertion "result.headers.Cache-Control ShouldEqual \"no-store, max-age=0\"" failed. expected: no-store, max-age=0  got: <nil> (owasp.securityheader.yml:138)
        • Feature-Policy PASS
          [info] This header has now been renamed to Permissions-Policy in the specification. (owasp.securityheader.yml:145)
        • Public-Key-Pins PASS
          [info] This header has been deprecated by all major browsers and is no longer recommended. Avoid using it, and update existing code if possible! (owasp.securityheader.yml:158)
        • Expect-CT PASS
          [info] This header will likely become obsolete in June 2021. Since May 2018 new certificates are expected to support SCTs by default. Certificates before March 2018 were allowed to have a lifetime of 39 months, those will all be expired in June 2021. (owasp.securityheader.yml:171)
        • X-XSS-Protection PASS
          [info] The X-XSS-Protection header has been deprecated by modern browsers and its use can introduce additional security issues on the client side. (owasp.securityheader.yml:186)
final status: FAIL
</details>

<details>
<summary>Venom run owasp.org</summary>
venom run --var="target_site=https://owasp.org" owasp.securityheader.yml


          [trac] writing venom.12.log
 • HTTP security response headers test suites (owasp.securityheader.yml)
        • Strict-Transport-Security FAIL
Testcase "Strict-Transport-Security", step #0-0: Assertion "result.headers.Strict-Transport-Security ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:16)
Testcase "Strict-Transport-Security", step #0-0: Assertion "result.headers.Strict-Transport-Security ShouldEqual \"max-age=31536000; includeSubDomains\"" failed. expected: max-age=31536000; includeSubDomains  got: <nil> (owasp.securityheader.yml:17)
        • X-Frame-Options FAIL
Testcase "X-Frame-Options", step #0-0: Assertion "result.headers.X-Frame-Options ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:27)
Testcase "X-Frame-Options", step #0-0: Assertion "result.headers.X-Frame-Options ShouldBeIn \"deny\" \"DENY\"" failed. expected '<nil>' in [deny DENY] but it wasnt (owasp.securityheader.yml:28)
        • X-Content-Type-Options FAIL
Testcase "X-Content-Type-Options", step #0-0: Assertion "result.headers.X-Content-Type-Options ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:38)
Testcase "X-Content-Type-Options", step #0-0: Assertion "result.headers.X-Content-Type-Options ShouldEqual \"nosniff\"" failed. expected: nosniff  got: <nil> (owasp.securityheader.yml:39)
        • Content-Security-Policy FAIL
Testcase "Content-Security-Policy", step #0-0: Assertion "result.headers.Content-Security-Policy ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:49)
        • X-Permitted-Cross-Domain-Policies FAIL
Testcase "X-Permitted-Cross-Domain-Policies", step #0-0: Assertion "result.headers.X-Permitted-Cross-Domain-Policies ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:60)
Testcase "X-Permitted-Cross-Domain-Policies", step #0-0: Assertion "result.headers.X-Permitted-Cross-Domain-Policies ShouldEqual \"none\"" failed. expected: none  got: <nil> (owasp.securityheader.yml:61)
        • Referrer-Policy FAIL
Testcase "Referrer-Policy", step #0-0: Assertion "result.headers.Referrer-Policy ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:71)
Testcase "Referrer-Policy", step #0-0: Assertion "result.headers.Referrer-Policy ShouldEqual \"no-referrer\"" failed. expected: no-referrer  got: <nil> (owasp.securityheader.yml:72)
        • Clear-Site-Data FAIL
Testcase "Clear-Site-Data", step #0-0: Assertion "result.headers.Clear-Site-Data ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:82)
Testcase "Clear-Site-Data", step #0-0: Assertion "result.headers.Clear-Site-Data ShouldEqual '\"cache\",\"cookies\",\"storage\"'" failed. expected: "cache","cookies","storage"  got: <nil> (owasp.securityheader.yml:83)
        • Cross-Origin-Embedder-Policy FAIL
Testcase "Cross-Origin-Embedder-Policy", step #0-0: Assertion "result.headers.Cross-Origin-Embedder-Policy ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:93)
Testcase "Cross-Origin-Embedder-Policy", step #0-0: Assertion "result.headers.Cross-Origin-Embedder-Policy ShouldEqual \"require-corp\"" failed. expected: require-corp  got: <nil> (owasp.securityheader.yml:94)
        • Cross-Origin-Opener-Policy FAIL
Testcase "Cross-Origin-Opener-Policy", step #0-0: Assertion "result.headers.Cross-Origin-Opener-Policy ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:104)
Testcase "Cross-Origin-Opener-Policy", step #0-0: Assertion "result.headers.Cross-Origin-Opener-Policy ShouldEqual \"same-origin\"" failed. expected: same-origin  got: <nil> (owasp.securityheader.yml:105)
        • Cross-Origin-Resource-Policy FAIL
Testcase "Cross-Origin-Resource-Policy", step #0-0: Assertion "result.headers.Cross-Origin-Resource-Policy ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:115)
Testcase "Cross-Origin-Resource-Policy", step #0-0: Assertion "result.headers.Cross-Origin-Resource-Policy ShouldEqual \"same-origin\"" failed. expected: same-origin  got: <nil> (owasp.securityheader.yml:116)
        • Permissions-Policy FAIL
Testcase "Permissions-Policy", step #0-0: Assertion "result.headers.Permissions-Policy ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:126)
Testcase "Permissions-Policy", step #0-0: Assertion "result.headers.Permissions-Policy ShouldEqual \"accelerometer=(), autoplay=(), camera=(), cross-origin-isolated=(), display-capture=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(self), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(), clipboard-write=(), gamepad=(), hid=(), idle-detection=(), interest-cohort=(), serial=(), unload=()\"" failed. expected: accelerometer=(), autoplay=(), camera=(), cross-origin-isolated=(), display-capture=(), encrypted-media=(), fullscreen=(), geolocation=(), gyroscope=(), keyboard-map=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), screen-wake-lock=(), sync-xhr=(self), usb=(), web-share=(), xr-spatial-tracking=(), clipboard-read=(), clipboard-write=(), gamepad=(), hid=(), idle-detection=(), interest-cohort=(), serial=(), unload=()  got: <nil> (owasp.securityheader.yml:127)
        • Cache-Control FAIL
Testcase "Cache-Control", step #0-0: Assertion "result.headers.Cache-Control ShouldNotBeNil" failed. expected: Not Nil but is was (owasp.securityheader.yml:137)
Testcase "Cache-Control", step #0-0: Assertion "result.headers.Cache-Control ShouldEqual \"no-store, max-age=0\"" failed. expected: no-store, max-age=0  got: <nil> (owasp.securityheader.yml:138)
        • Feature-Policy PASS
          [info] This header has now been renamed to Permissions-Policy in the specification. (owasp.securityheader.yml:145)
        • Public-Key-Pins PASS
          [info] This header has been deprecated by all major browsers and is no longer recommended. Avoid using it, and update existing code if possible! (owasp.securityheader.yml:158)
        • Expect-CT PASS
          [info] This header will likely become obsolete in June 2021. Since May 2018 new certificates are expected to support SCTs by default. Certificates before March 2018 were allowed to have a lifetime of 39 months, those will all be expired in June 2021. (owasp.securityheader.yml:171)
        • X-XSS-Protection PASS
          [info] The X-XSS-Protection header has been deprecated by modern browsers and its use can introduce additional security issues on the client side. (owasp.securityheader.yml:186)
final status: FAIL
</details>

**Comment by righettod** [comment]
You seems to use the version **1.1.0** of venom:

![image](https://github.com/user-attachments/assets/bd85a60a-df1b-48b9-a87b-01a18d9337b4)

Made a try with the version **1.2.0** via a prior `venom update` command 😉

Indeed, there is a change in the behavior with the case with the **version 1.2.0**:

![image](https://github.com/user-attachments/assets/e299c055-3df6-413a-8803-8a8c9fbf2722)

**Comment by HugoVG** [comment]
That worked. apparently the install from venom got me the older version

**Comment by righettod** [comment]
Happy to have helped you 😉
